### ISSUE TITLE
TransformSetterIntercept Not Found

### ISSUE THREAD

**Issue by xujiezhige** [handzlikchris/Unity.TransformSetterInterceptor#1]
My unity version is 2018.2.17f1. 
![1](https://user-images.githubusercontent.com/8527792/74890100-0a4e0b80-53be-11ea-8b82-d70832860484.png)

**Comment by handzlikchris** [comment]
Hi, apologies for late reply I've not been monitoring this one.

From the error it looks like the contents of manifest.json could be wrong. Potentially a typo or something similar.

If you want to post it here I'll have a look.

Thanks,
Chris
