### ISSUE TITLE
Looping compilation?

### ISSUE THREAD

**Issue by malkere** [handzlikchris/Unity.TransformSetterInterceptor#2]
After importing the package I've been
compiling scripts -> writing package items -> importing scripts -> repeat
for 22 minutes now.
I'm hoping it's going through my assemblies one by one, and will finish soon, but it's getting ridiculous.
2018.4.23

**Comment by handzlikchris** [comment]
Hi, perhaps there's some issue with FodyWeavers.xml? That's what can trigger recompile, but shouldn't go in a loop - unless something else is triggering change.

You can also try https://github.com/handzlikchris/Unity.MissingUnityEvents - which is taking slightly different approach and not re-weaving your files. Instead it'll change Unity dlls just once.
