### ISSUE TITLE
No observable interception

### ISSUE THREAD

**Issue by werkt** [handzlikchris/Unity.TransformSetterInterceptor#4]
Following the setup instructions has not resulted in any logging or filterable calls to transform modifications:

On Unity 2019.4.0f1
I observed the `'A configuration lists 'TransformSetterCallRedirector' but the assembly file wasn't found in the search paths'` error, to be somewhat confident that Malimbe was running at all. I modified the ModuleWeaver.cs to inspire a recompile, and the error went away, again as prescribed.

I pressed play on my scene, and observed changes to my object under inspection's transform.

No new log messages were observed at this point.

I created an empty game object at the root with the TransformSetterInterceptorFilter.cs script, assigning the object transform that I wanted filtered.

Again, no new messages were observed.

I attached via VS to the Unity debugger port, setting a breakpoint on LogIfMatchesFilter. This breakpoint was not encountered, and the IDE indicated that no symbols were available for the TransformSetterCallInterceptor.cs unit script from the package import. Likewise, no joy with attaching directly to the unity process and setting a breakpoint.

Is there any proper way to observe whether the interceptor is properly woven into the products used in play mode? Am I doing this incorrectly? Are there better debugging steps you would recommend?

**Comment by handzlikchris** [comment]
Hi,

You can have a look with some decompiler like dnSpy directly into Assembly-CSSharp that Editor picks up, usually somewhere in `Library\ScriptAssemblies`. If calls are correctly intercepted then you'll see a call to interceptor class and not whatever it's intercepting for.

Generally if the breakpoint is not hit I'd think it's not woven at all. Debugging wise attaching to `ModuleWeaver` si probably your best bet.

There could be easier solution for you - this tool was somewhat superseded by `https://github.com/handzlikchris/Unity.MissingUnityEvents` - which also uses weaving but it does so with actual Unity assemblies (so it's just one time operation) and adds actuall c# events to them which are easier to work with than setting up interceptor class.

Hope that helps.

Thanks,
Chris
